#!/usr/bin/env bash
# script that will display information about subdomains

info_sub() {
    domain="$1"
    subdomain="$2"

    if [ -z "$subdomain" ]
    then
        subdomains=("www" "lb-01" "web-01" "web-02")
    else
        subdomains=("$subdomain")
    fi

    for sub in "${subdomains[@]}"
    do
        answer=$(dig "$sub.$domain" | awk '/ANSWER SECTION/ {getline; print}')
        record=$(echo "$answer" | awk '{print $4}')
        dest=$(echo "$answer" | awk '{print $5}')
        echo "The subdomain $sub is a $record record and points to $dest"
    done
}

info_sub "$1" "$2"
