#!/usr/bin/env bash
# Configures a new Ubuntu server with a HAproxy load-balancer

sudo apt-get -y update
sudo apt-get -y install --no-install-recommends software-properties-common
sudo add-apt-repository -y ppa:vbernat/haproxy-2.8
sudo apt-get -y install haproxy=2.8.\*

echo "ENABLED=1" | sudo tee -a /etc/default/haproxy

new_conf="\
frontend http_front
    bind *:80
    default_backend http_back
    
backend http_back
    balance roundrobin
    server web-01 18.234.107.21:80 check
    server web-02 18.210.17.1:80 check"
echo "${new_conf}" | sudo tee /etc/haproxy/haproxy.cfg

sudo service haproxy restart
