#!/usr/bin/env bash
# a Bash script that:
# Creates the file /var/run/myscript.pid containing its PID
# Displays To infinity and beyond indefinitely
# Displays I hate the kill command when receiving a SIGTERM signal
# Displays Y U no love me?! when receiving a SIGINT signal
# Deletes the file /var/run/myscript.pid and terminates itself when receiving a SIGQUIT or SIGTERM signal
file="/var/run/myscript.pid"
echo "$$" > $file

term_sig () {
    echo "I hate the kill command"
    quit_term_sig
}

int_sig () {
    echo "Y U no love me?!"
}

quit_term_sig () {
    rm $file
    exit
}

trap int_sig SIGINT
trap term_sig SIGTERM
trap quit_term_sig SIGQUIT

while (( 1 )); do
    echo "To infinity and beyond"
    sleep 2
done
