#!/usr/bin/env bash
# a Bash script that displays To infinity and beyond indefinitely
# I am invincible!!! when receiving a SIGTERM signal
inv () {
    echo "I am invincible!!!"
}

trap inv 15

while (( 1 )); do
    echo "To infinity and beyond"
    sleep 2
done
